### ISSUE TITLE
require_question_responses() result should be cached in the session

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_securityquestions#10]
ie if you have already answered the questions in this session, then set something so we don't hit the db with another 2 calls on every page.

Likewise if we allow optional questions in the grace period rollout, and we have chosen to ignore them, then put this in the session too.

Do the capability check before all of these other checks as it should be the fastest

**Comment by Peterburnett** [comment]
Closed in PR #18
