### ISSUE TITLE
Setting config value < default throws error when resetting password

### ISSUE THREAD

**Issue by sarahjcotton** [catalyst/moodle-tool_securityquestions#108]
When setting `tool_securityquestions | answerquestions` to 1 (default is 2), the following error is thrown when resetting a password: 
```
Warning: foreach() argument must be of type array|object, int given in /var/www/moodlepgsql/admin/tool/securityquestions/locallib.php on line 446

Warning: Undefined array key 0 in /var/www/moodlepgsql/admin/tool/securityquestions/locallib.php on line 205
```
I'm happy to fix but would like to clarify the intended behaviour. Should 2 be the minimum number of questions answered, therefore fix by adding validation to the settings field, or fix to allow a value less than the default value to be used?

Tested against:
• Ubuntu 22.04.1 LTS
• mysql 8.0.31
• postgres (14.0 (Debian 14.0-1.pgdg110+1))
• php 8.0.25
• Branch: master

**Comment by sarahjcotton** [comment]
@brendanheywood do you have any advice on this one please?

**Comment by Peterburnett** [comment]
This should be locked down to prevent anything less that 2 IMO. 1 is typically not enough for a high level of security, especially with a small question set.
