### ISSUE TITLE
Instead of just a mandatory swith for requiring security questions, have a grace period

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_securityquestions#24]
Similar to the 2fa grace setting in gitlab

![image](https://user-images.githubusercontent.com/187449/63815440-e7471f80-c977-11e9-814c-598b0c857294.png)

* [ ] simplest: just have a grace period from when the account was logged in (not created) vs now - this will work for all new accounts
* [x] slightly more complicated, for legacy accounts store when they first logged in *after* the security questions was enabled. Requires storing that date per user, possibly as a user preference api.

**Comment by Peterburnett** [comment]
Implemented in PR #29
