### ISSUE TITLE
Always require_login if require_recent_login does not exist

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_securityquestions#5]
https://github.com/catalyst/moodle-tool_securityquestions/blob/83b3340d25ca4dd5ba45b1bb2a9d93ffca3a8bb0/set_responses.php#L46

**Comment by brendanheywood** [comment]
Also move the require_recent_login to right at the top, before you use the $USER global

**Comment by Peterburnett** [comment]
Finalised in PR #18
