### ISSUE TITLE
Logout from initial prompt page doesnt work

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_securityquestions#65]
1) login, get redirected to security question page
2) click logout, goes to home page, still logged in
3) click logout again works

Note: Might be a saml related bug

**Comment by Peterburnett** [comment]
This actually appears to be an MFA related bug. After disabling MFA on my devbox, logout worked just fine. Logged an issue here: https://github.com/catalyst/moodle-tool_mfa/issues/165
