### ISSUE TITLE
might be worth tightening up tool_securityquestions_read_questions_file()

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_securityquestions#71]
stuff like this makes me nervous:
   
        $path = $CFG->wwwroot.$file;
        tool_securityquestions_read_questions_file($path);

$file does come from config so only the admin should be able to set it, but is basically raw data and then tool_securityquestions_read_questions_file just accepts the path.

might be nice to tidy this up a bit to prevent directory traversal etc.

**Comment by brendanheywood** [comment]
I'm inclined to say that reading these from a file is a bit of overkill. It's not that much work to ad 10-20 records. If we do want something like this I'd lean towards an admin text area config setting which holds all the questions and that gets processed into the tool_securityquestions table

**Comment by danmarsden** [comment]
Good call - it did look a bit weird!
